version: "3.8"

services:
  app:
    image: node:12-alpine
    # command: sh -c "npm install && npm run build && node server/index.js"
    command: sh -c "node server/index.js && nodemon server/index.js"

    ports:
      - 9000:9000
    working_dir: /app
    volumes:
      - ./:/app

volumes:
  express-data: